# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import GeorisqueApi
from GeorisqueApi.api.azi_api import AZIApi  # noqa: E501
from GeorisqueApi.rest import ApiException


class TestAZIApi(unittest.TestCase):
    """AZIApi unit test stubs"""

    def setUp(self):
        self.api = AZIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_recherche_risques7(self):
        """Test case for recherche_risques7

        Lister les Atlas de Zones Inondables (AZI) recensés sur le territoire concerné  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
