# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import GeorisqueApi
from GeorisqueApi.api.familles_risque_ppr_api import FamillesRisquePPRApi  # noqa: E501
from GeorisqueApi.rest import ApiException


class TestFamillesRisquePPRApi(unittest.TestCase):
    """FamillesRisquePPRApi unit test stubs"""

    def setUp(self):
        self.api = FamillesRisquePPRApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_recherche_risque(self):
        """Test case for recherche_risque

        Lister les familles de risques  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
