# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import GeorisqueApi
from GeorisqueApi.models.zonage_argile import ZonageArgile  # noqa: E501
from GeorisqueApi.rest import ApiException


class TestZonageArgile(unittest.TestCase):
    """ZonageArgile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testZonageArgile(self):
        """Test ZonageArgile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GeorisqueApi.models.zonage_argile.ZonageArgile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
