# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import GeorisqueApi
from GeorisqueApi.models.etat_ppr import EtatPPR  # noqa: E501
from GeorisqueApi.rest import ApiException


class TestEtatPPR(unittest.TestCase):
    """EtatPPR unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEtatPPR(self):
        """Test EtatPPR"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GeorisqueApi.models.etat_ppr.EtatPPR()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
