# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import GeorisqueApi
from GeorisqueApi.models.casias_dto import CasiasDto  # noqa: E501
from GeorisqueApi.rest import ApiException


class TestCasiasDto(unittest.TestCase):
    """CasiasDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCasiasDto(self):
        """Test CasiasDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GeorisqueApi.models.casias_dto.CasiasDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
